[package]
name = "protocol-modbus-tcp"
version = "0.1.0"
edition = "2021"

[dependencies]
protocol-core = { path = "../protocol-core"  }
tokio = { version = "1.28", features = ["full"] }
tracing = "0.1"
#为啥选这个库,因为测试通过的
modbus = "1.0"
derive-getters = "0.3.0"
async-trait = "0.1"
thiserror = "1"
