name: Build-Linux

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Environment
        run: |
          rustup target add  x86_64-unknown-linux-musl
          sudo apt update
          sudo apt install musl-tools

      - name: Build
        run: cargo build --release --target x86_64-unknown-linux-musl

      - name: Archive artifacts
        run: |
          cp target/release/lotus-bridge* ./
          tar -czvf lotus-bridge.tar.gz ./lotus-bridge* conf sqlite.db
        if: success()

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: latest-package
          path: |
            lotus-bridge.tar.gz